packages:
  - cosing-plus
  - online-common/internal/*
  - online-common/internal/lint-configs/*
catalog:
  '@ant-design/icons-vue': ^7.0.1
  '@antv/g2plot': ^2.4.32
  '@antv/l7': ^2.22.3
  '@antfu/eslint-config': ^2.27.3
  '@intlify/unplugin-vue-i18n': ^6.0.1
  '@ctrl/tinycolor': ^4.1.0
  '@commitlint/cli': ^18.6.1
  '@commitlint/config-conventional': ^18.6.3
  '@mistjs/cli': 0.0.1-beta.9
  '@mistjs/vite-plugin-preload': ^0.0.1
  '@types/crypto-js': ^4.2.2
  '@types/fs-extra': ^11.0.4
  '@types/file-saver': ^2.0.7
  '@types/lodash': ^4.17.13
  '@types/lodash-es': ^4.17.12
  '@types/node': ^20.17.6
  '@types/treeify': ^1.0.3
  '@vitejs/plugin-vue': ^5.2.0
  '@vitejs/plugin-vue-jsx': ^4.1.0
  '@vue/test-utils': ^2.4.6
  '@v-c/utils': ^0.0.26
  '@vueuse/core': ^10.11.1
  ant-design-vue: ^4.2.6
  axios: ^1.7.7
  antdv-component-resolver: ^1.0.7
  antdv-style: 0.0.1-beta.2
  changelogen: ^0.5.7
  cross-env: ^7.0.3
  crypto-js: ^4.2.0
  directory-tree: ^3.5.2
  dayjs: ^1.11.13
  dotenv: ^16.4.5
  esbuild: ^0.20.2
  eslint: ^9.14.0
  eslint-flat-config-utils: ^0.3.1
  esno: ^0.17.0
  execa: ^8.0.1
  fs-extra: ^11.2.0
  file-saver: ^2.0.5
  globals: ^15.13.0
  husky: ^9.1.6
  jsdom: ^22.1.0
  jsencrypt: ^3.3.2
  lodash-es: ^4.17.21
  less: ^4.2.0
  lint-staged: ^14.0.1
  lodash: ^4.17.21
  mitt: ^3.0.1
  nitropack: ^2.10.4
  npm-run-all: ^4.1.5
  picocolors: ^1.1.1
  pinia: ^2.2.6
  pkg-types: ^1.2.1
  rollup-plugin-visualizer: ^5.12.0
  treeify: ^1.1.0
  ts-node: ^10.9.2
  typescript: ~5.5.4
  vue: ^3.5.12
  unbuild: ^3.0.0-rc.11
  unocss: ^0.57.7
  unocss-preset-chinese: ^0.3.3
  unocss-preset-ease: ^0.0.3
  unplugin-auto-import: ^0.16.7
  unplugin-config: ^0.1.5
  unplugin-vue-components: ^0.26.0
  vue-i18n: ^9.14.1
  vue-router: ^4.4.5
  vite: ^5.4.11
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.3.0
  vite-plugin-html: ^3.2.2
  vite-plugin-pwa: ^0.21.1
  vite-plugin-vue-devtools: ^7.6.8
  vitest: ^0.34.6
  vue-tsc: ^2.1.10
